[RDS]
HOST=st.secrets["HOST"]
PORT=st.secrets["PORT"]
USER=st.secrets["USER"]
DATABASE=st.secrets["DATABASE"]
PASSWORD=st.secrets["PASSWORD"]
[AZURE]
HOST=st.secrets["HOST"]
PORT=st.secrets["PORT"]
USER=st.secrets["USER"]
DATABASE=st.secrets["DATABASE"]
PASSWORD=st.secrets["PASSWORD"]


